### ISSUE TITLE
Overlapping headings

### ISSUE THREAD

**Issue by britishtea** [devinhunt/typebase.css#16]
I'm seeing overlapping headings on Safari 9.0, OS X El Capitan.

![screen shot 2015-10-04 at 18 27 50](https://cloud.githubusercontent.com/assets/791871/10268857/b1da988c-6ac5-11e5-82a3-819b15c1cec0.png)

**Comment by yoshuawuyts** [comment]
This has little to do with `typebase`, and more with your window width. Typebase doesn't change text overflowing / doesn't do breakpoints. The README also states that mobile support isn't quite fleshed out.

If you want to adjust this, you can probably override the variable declarations by wrapping them inside breakpoints (so they work on smaller screen sizes) and / or change the text-overflow settings for the headings.

That said, if you can figure out a reasonable approach to fix it, I'm sure PRs would be greatly appreciated.

**Comment by britishtea** [comment]
I don't think window width is the issue. Even with a maximum window width the headings overlap on a 13" display.

![screen shot 2015-10-04 at 19 42 38](https://cloud.githubusercontent.com/assets/791871/10269205/2c13ffc6-6ad0-11e5-8104-18f4f299aae8.png)

**Comment by mankittens** [comment]
word-wrap: break-word;

will trigger the behavior you're expecting.

**Comment by cozmo** [comment]
I think this may not be a bug as such, but worth considering optimizing for a certain minimumn screen size? For me it starts to look broken/bad at roughly 1300px. 

May try to fix this in a PR. I'd settle for looking good at width >1024 or maybe even 1296?

**Comment by devinhunt** [comment]
This is problem with how the (hastily created) specimen sheet is setup, and not typebase.css. It is indeed overflow from the longer words. `word-wrap: break-word` is a quick fix, though it would still look crap on mobile. If someone wants to tackle this, i'll review the PR asap.
