### ISSUE TITLE
Add a License 

### ISSUE THREAD

**Issue by K4orta** [devinhunt/typebase.css#17]
Please add some kind of license(MIT, GPL, ECT.) to the repo so people who work at organizations with legal departments can use this project without making their lawyer friends unhappy.

**Comment by breadtk** [comment]
:+1:

**Comment by Calinou** [comment]
:+1: for [The MIT License](http://opensource.org/licenses/MIT).

**Comment by austinpray** [comment]
:+1: MIT

**Comment by yoshuawuyts** [comment]
It's MIT licensed - https://github.com/devinhunt/typebase.css/blob/master/typebase.css#L1

**Comment by Calinou** [comment]
> It's already MIT licensed - https://github.com/devinhunt/typebase.css/blob/master/typebase.css#L1

A copy of the license should be added to the repository, and the license should be added to `package.json`.

**Comment by devinhunt** [comment]
Thanks guys, this was me being lazy. I'm looking at @Calinou's #20 now and will merge shortly.
