### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by sunnysingh** [devinhunt/typebase.css#24]
I tried running `npm install typebase.css` but it said that the package is not published to the registry. Since you already have a `package.json` file, can you fix the registry listing?

Awesome project by the way.

**Comment by yoshuawuyts** [comment]
Looks like it wasn't published indeed. For CSS it might be recommended to add the
```js
{ "main": "index.css", "style": "index.css" }
```
values to `package.json`. This way `typebase.css` without a problem with a bunch of CSS processors that rely on these values.

From there on out an `npm publish` should probably suffice. Cheers!

**Comment by devinhunt** [comment]
Should typebase.css be published to NPM? It doesn't strike me as JS module. Thoughts?

**Comment by sunnysingh** [comment]
@devinhunt I've been using PostCSS lately, and the @import plugin allows you to import directly from Node or Bower modules without having to specify the full path, just like `require()` in JS. I think Less/Sass can do this too as long as you're using Webpack I believe.

In short, it'd be useful for devs that use NPM as their only package manager.

**Comment by neverfox** [comment]
It definitely should be. NPM has support for pure CSS libraries, and with everyone using webpack these days, it's expected that your CSS frameworks will be installed like any other node.js dependency.

**Comment by yoshuawuyts** [comment]
I published https://github.com/sheetify/css-type-base a while back which was extracted from this repo; until this has been published on npm it might be worth using. I hope it's of any use to you :sparkles:

**Comment by devinhunt** [comment]
Sorry for the wait! Now live on NPM as https://www.npmjs.com/package/typebase.css. 

LMK if you have any issues / suggestions for the structure.
