### ISSUE TITLE
Responsive Typography

### ISSUE THREAD

**Issue by jkinley** [devinhunt/typebase.css#28]
How do you propose to use this responsively? I used media queries to change the font-size, like so:

```
@media screen and (min-width:40rem) {
html {
    font-size: $baseFontSize / 16 * 105%;
}
}

@media screen and (min-width: 60rem) {
html {
    font-size: $baseFontSize / 16 * 110%;
}
}

```

Does anyone have an alternative idea?

**Comment by devinhunt** [comment]
I recommend choosing what "optimal" font-size you would like to use at different screen sizes. For example, here's the excerpt from my site, hailpixel.com: 

```
html {
  /* Change default typefaces here */
  &:extend(.bodyType);
  color: #222;

  // Smaller screens
  font-size: (@baseFontSize - 4) / 16 * 100%;

  // Larger screens
  @media (min-width: @smallScreenSize) {
    font-size: @baseFontSize / 16 * 100%;
  }
}
```

**Comment by drawcard** [comment]
For headings you could also consider using http://fittextjs.com/ for proportionally scaling type (not recommended for body text however)
