### ISSUE TITLE
Convert to Em

### ISSUE THREAD

**Issue by Blackglade** [devinhunt/typebase.css#29]
I know many developers (including me) prefer to use em instead of rem, any chance that this boilerplate file could be converted?

Also just wanna reference this article in here since rem isn't really consistent across all browsers when you use media queries:

http://zellwk.com/blog/media-query-units/

**Comment by devinhunt** [comment]
I like this idea in theory. The original reason for using `rem` over `em` was to maintain consistent type size across the entire page, regardless of nesting. I don't want typebase to dictate how the document is structured. 

Could you put together a gist / PR that shows how we could accomplish this using `em` as the base unit?
