### ISSUE TITLE
Amazing code!

### ISSUE THREAD

**Issue by endling9973** [devinhunt/typebase.css#31]
Hey, 

Can you please elaborate how you calculated the proper rem for everything? I want to be able to perfect the grid to my current need but I can't put my head around the logic behind. It would be great if you could give me some help.

I'm immensely thankful anyways.

PS: I wanna try to help. I love typography.

**Comment by devinhunt** [comment]
The idea is pretty simple and is quickly becoming a little dated. 

One of the core tenets of this project is to use rems to maintain a strong vertical gird (as 'seen' in the demo). In CSS `1em = 12pt = 16px = 100%`. So, with that in mind the calculation `font-size: @baseFontSize / 16 * 100%;` converts a pixel font size (`22px` for example) to a percentage. This percentage plays nicely across multiple devices (note: this has become less of an issue in recent years). 

With that set for the whole document, you can use rem's to express relative font-sizes throughout your project.

**Comment by endling9973** [comment]
Thank you very much.
