### ISSUE TITLE
New release on NPM

### ISSUE THREAD

**Issue by liarco** [devinhunt/typebase.css#35]
Hi @devinhunt, the [NPM package](https://www.npmjs.com/package/typebase.css) for this library is stuck to `v0.5.0` which is a [tag that is not up to date with the latest features](https://github.com/devinhunt/typebase.css/releases/tag/v0.5.0).
Could you please release a new version? Is there any ETA?

Thank you for your time.

**Comment by devinhunt** [comment]
Done! Sorry for the delay.
