### ISSUE TITLE
Add project to Bower

### ISSUE THREAD

**Issue by novabyte** [devinhunt/typebase.css#9]
It'd be great if you could add a `bower.json` file for this project so that it can be retrieved as a [Bower](http://bower.io) package.

You can see an example of one for Normalize.css here:
https://github.com/necolas/normalize.css/blob/master/bower.json

**Comment by tmaiaroto** [comment]
+1

**Comment by josephmilla** [comment]
+1

**Comment by vaeum** [comment]
+1

**Comment by devinhunt** [comment]
Done with https://github.com/devinhunt/typebase.css/commit/70355eeef20104549c518ca37f1d5b8fc133597f. 

LMK if anyone has issues with the current Bower structure.
